baseURL = "www.example.com"
languageCode = "en-us"
title = "Bither Sverige"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.homepage]
  show_call_box = true
  hide_view_all_services = false

  [params.logo]
  mobile = "images/fierce-ant.svg"
  desktop = "images/13.svg"
  desktop_height = "36px"
  alt = "  Evolve Wisely"

  [params.homepage_meta_tags]
  meta_description = "Din IT-tjänsteleverantör"
  meta_og_title = "Bither Sverige"
  meta_og_type = "website"
  meta_og_url = "https://bither.se"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

  [params.footer]
  copyright_text = "Bithe"

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
